on:
  push:
    branches:
      - main
      - master
jobs:
  meu-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo " 🎉​ The job was automatically triggered by a event."
      - run: echo " 🐧 ​job está rodando em um servidor hospedado pelo GitHub"

  meu-segundo-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo 📅 Data e hora atual $(TZ='America/Sao_Paulo' date +'%d/%m/%Y %H:%M:%S')
      
      - run: ls -la 
      
      - uses: actions/checkout@v6

      - run: ls -la 